version: '3.9'

services:
  app:
    image: 'todo-application:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

  db:
    image: 'postgres:latest'
    restart: always
    container_name: db_postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/db.sq
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks_db

volumes:
  pg_data:
    driver: local