version: '3.9'

services:

  db:
    image: 'postgres:9.6.8'
    restart: always
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks_db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d tasks_db'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
  app:
    image: 'todo-application:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
volumes:
  pg_data:
    driver: local